# -----------------------------------------------------------------------------
# Prescient Coding Challenge 2026 -- backtest harness (R).
#
# DO NOT EDIT THIS FILE. Your submission is `solution.R` and nothing else. Any
# change to this file is a disqualification (we diff it).
#
# The harness owns the walk-forward loop. On each rebalance date it hands your
# generate_weights() function a `hist` list containing only data STRICTLY BEFORE
# that date, takes the weights you return, charges trading costs, checks the
# constraints and accumulates the portfolio return. Because you never receive
# future data, look-ahead bias is impossible rather than merely forbidden.
#
# This file uses base R only -- nothing to install.
#
# Run it:  Rscript harness.R
# -----------------------------------------------------------------------------

# ---- problem definition: these are the rules, in code -----------------------

ASSETS <- c("SA_EQUITY",      # FTSE/JSE All Share, total return, ZAR
            "GLOBAL_EQUITY",  # MSCI World net total return, converted to ZAR
            "SA_BONDS",       # FTSE/JSE All Bond Index, total return
            "SA_CASH",        # STeFI Composite
            "SA_PROPERTY",    # FTSE/JSE SA Listed Property, total return
            "GOLD")           # gold spot per oz, converted to ZAR

# The benchmark: a fixed-weight South African balanced fund, rebalanced daily
# at zero cost (it is an index, not a portfolio).
BENCHMARK <- c(SA_EQUITY = 0.400, GLOBAL_EQUITY = 0.200, SA_BONDS = 0.250,
               SA_CASH = 0.075, SA_PROPERTY = 0.050, GOLD = 0.025)[ASSETS]

# How far any single asset may sit from its benchmark weight.
ACTIVE_BAND <- 0.10

# How much active weight you may run in total: sum over assets of
# |weight - benchmark weight|. This is your risk budget.
ACTIVE_BUDGET <- 0.40

# Minimum average total active weight over an evaluation window. A portfolio
# that never leaves the benchmark is not an answer to the question.
MIN_ACTIVE_WEIGHT <- 0.05

# Hard cap on commodity exposure, whatever the band allows.
EQUITY     <- c("SA_EQUITY", "GLOBAL_EQUITY")
EQUITY_CAP <- 0.75
GOLD_CAP <- 0.10

TRADING_DAYS <- 252

# One-way trading cost in basis points of the traded amount.
COSTS_BPS <- c(SA_EQUITY = 15, GLOBAL_EQUITY = 20, SA_BONDS = 8,
               SA_CASH = 1, SA_PROPERTY = 35, GOLD = 25)[ASSETS]

# Covariance estimator offered as an optional tool via hist$cov() and hist$te().
# Nothing in the rules depends on it -- use it only if you want to.
COV_WINDOW <- 250
COV_LAMBDA <- 0.97

# Evaluation windows.
PRACTICE_WINDOW <- as.Date(c("2025-01-02", "2025-12-31"))
ROBUSTNESS_WINDOWS <- list(
  "2015" = as.Date(c("2015-01-02", "2015-12-31")),   # ZAR shock
  "2016" = as.Date(c("2016-01-04", "2016-12-30")),   # post-Nenegate, commodity rebound
  "2020" = as.Date(c("2020-01-02", "2020-12-31")),   # covid
  "2022" = as.Date(c("2022-01-03", "2022-12-31"))    # inflation shock
)

.TOL <- 1e-6

# ---- data -------------------------------------------------------------------

#' Load the asset and macro files.
#'
#' Returns a list with `returns`, `prices` and `macro` matrices. All three are
#' indexed by date: rownames are date strings and `dates` holds the parsed Dates.
load_data <- function(data_dir = "data") {
  assets <- read.csv(file.path(data_dir, "data_assets.csv"), stringsAsFactors = FALSE)
  macro  <- read.csv(file.path(data_dir, "data_macro.csv"),  stringsAsFactors = FALSE)

  assets$datestamp <- as.Date(assets$datestamp)
  macro$datestamp  <- as.Date(macro$datestamp)

  dates <- sort(unique(assets$datestamp))
  to_matrix <- function(value_col) {
    m <- matrix(NA_real_, nrow = length(dates), ncol = length(ASSETS),
                dimnames = list(as.character(dates), ASSETS))
    ri <- match(assets$datestamp, dates)
    ci <- match(assets$asset_code, ASSETS)
    keep <- !is.na(ri) & !is.na(ci)
    m[cbind(ri[keep], ci[keep])] <- assets[[value_col]][keep]
    m
  }

  macro_cols <- setdiff(names(macro), "datestamp")
  macro_m <- as.matrix(macro[, macro_cols, drop = FALSE])
  rownames(macro_m) <- as.character(macro$datestamp)

  list(returns = to_matrix("return"), prices = to_matrix("price"),
       macro = macro_m, dates = dates, macro_dates = macro$datestamp)
}

# ---- the object your function receives --------------------------------------

#' Build the history object passed to generate_weights().
make_history <- function(date, returns, prices, macro) {
  self <- list(date = date, returns = returns, prices = prices, macro = macro,
               assets = ASSETS, benchmark = BENCHMARK)

  #' Total absolute active weight: sum of |weight - benchmark weight|.
  #' This is the number rule 3 tests against ACTIVE_BUDGET.
  self$active_weight <- function(weights) {
    sum(abs(as_weight_vector(weights) - BENCHMARK))
  }

  # ---- optional extras. No rule depends on these. ----
  cov_cache <- NULL
  self$cov <- function() {
    if (is.null(cov_cache)) {
      n <- nrow(self$returns)
      if (n < 20) stop("not enough history to estimate covariance")
      x <- self$returns[max(1, n - COV_WINDOW + 1):n, , drop = FALSE]
      x <- sweep(x, 2, colMeans(x), "-")
      w <- COV_LAMBDA ^ ((nrow(x) - 1):0)
      w <- w / sum(w)
      cov_cache <<- t(x * w) %*% x * TRADING_DAYS
    }
    cov_cache
  }

  self$te <- function(weights) {
    active <- as_weight_vector(weights) - BENCHMARK
    sqrt(max(as.numeric(t(active) %*% self$cov() %*% active), 0))
  }

  self
}

#' Coerce a named vector / list of weights into ASSETS order.
as_weight_vector <- function(weights) {
  if (is.list(weights)) weights <- unlist(weights)
  if (!is.null(names(weights))) {
    missing <- setdiff(ASSETS, names(weights))
    if (length(missing) > 0)
      stop(sprintf("generate_weights() returned no weight for: %s",
                   paste(missing, collapse = ", ")))
    weights <- weights[ASSETS]
  } else if (length(weights) != length(ASSETS)) {
    stop(sprintf("expected %d weights, got %d", length(ASSETS), length(weights)))
  }
  out <- as.numeric(weights)
  names(out) <- ASSETS
  out
}

# ---- constraint checking ----------------------------------------------------

#' Return a character vector of constraint breaches (empty means feasible).
check_weights <- function(w, hist) {
  problems <- character(0)
  if (any(!is.finite(w))) return("weights contain NA or non-finite values")

  active <- w - BENCHMARK

  if (abs(sum(w) - 1) > 1e-4)
    problems <- c(problems, sprintf("weights sum to %.6f, must sum to 1", sum(w)))

  for (a in ASSETS)
    if (w[[a]] < -.TOL)
      problems <- c(problems, sprintf("%s weight %.4f is negative", a, w[[a]]))

  for (a in ASSETS)
    if (abs(active[[a]]) > ACTIVE_BAND + .TOL)
      problems <- c(problems, sprintf(
        "%s is %+.2f%% away from its benchmark weight, outside the +/-%.0f%% band",
        a, 100 * active[[a]], 100 * ACTIVE_BAND))

  total <- sum(abs(active))
  if (total > ACTIVE_BUDGET + .TOL)
    problems <- c(problems, sprintf("total active weight %.2f%% above the %.0f%% budget",
                                    100 * total, 100 * ACTIVE_BUDGET))

  equity <- sum(w[EQUITY])
  if (equity > EQUITY_CAP + .TOL)
    problems <- c(problems, sprintf("total equity %.2f%% above the %.0f%% cap",
                                    100 * equity, 100 * EQUITY_CAP))

  if (w[["GOLD"]] > GOLD_CAP + .TOL)
    problems <- c(problems, sprintf("GOLD weight %.2f%% above its %.0f%% cap",
                                    100 * w[["GOLD"]], 100 * GOLD_CAP))
  problems
}

# ---- the walk-forward loop --------------------------------------------------

#' Walk forward from `start` to `end`, calling generate_weights each day.
run_backtest <- function(generate_weights, params, start, end,
                         data = NULL, verbose = TRUE, on_breach = "raise") {
  if (!on_breach %in% c("raise", "benchmark"))
    stop("on_breach must be 'raise' or 'benchmark'")
  if (is.null(data)) data <- load_data()
  start <- as.Date(start); end <- as.Date(end)

  eval_idx <- which(data$dates >= start & data$dates <= end)
  if (length(eval_idx) == 0)
    stop(sprintf("no trading days between %s and %s", start, end))

  cost_vec <- COSTS_BPS / 10000
  prev <- BENCHMARK                      # you start the window holding the benchmark
  breaches <- character(0)
  rows <- vector("list", length(eval_idx))

  for (k in seq_along(eval_idx)) {
    i <- eval_idx[k]
    date <- data$dates[i]

    hist <- make_history(
      date    = date,
      returns = data$returns[seq_len(i - 1), , drop = FALSE],
      prices  = data$prices[seq_len(i - 1), , drop = FALSE],
      macro   = data$macro[data$macro_dates < date, , drop = FALSE]
    )

    w <- as_weight_vector(generate_weights(hist, prev, params))

    problems <- check_weights(w, hist)
    if (length(problems) > 0) {
      breaches <- c(breaches, sprintf("%s: %s", date, paste(problems, collapse = "; ")))
      # Grading mode: hold the benchmark for the day rather than void the
      # window. The team forfeits its view, which cannot be gamed into a gain.
      if (on_breach == "benchmark") w <- BENCHMARK
    }

    traded   <- abs(w - prev)
    cost     <- sum(traded * cost_vec)
    realised <- data$returns[i, ]
    gross    <- sum(w * realised)

    rows[[k]] <- c(
      list(datestamp = date, port_return_gross = gross, cost = cost,
           port_return = gross - cost, bm_return = sum(BENCHMARK * realised),
           turnover = sum(traded) / 2,
           active_weight = sum(abs(w - BENCHMARK)),
           ex_ante_te = hist$te(w)),            # informational only
      setNames(as.list(w), paste0("w_", ASSETS))
    )
    prev <- w
  }

  if (length(breaches) > 0 && on_breach == "raise") {
    more <- if (length(breaches) > 15)
      sprintf("\n  ... and %d more", length(breaches) - 15) else ""
    stop(sprintf("Constraint breaches on %d day(s):\n  %s%s", length(breaches),
                 paste(head(breaches, 15), collapse = "\n  "), more))
  }

  bt <- do.call(rbind.data.frame, c(rows, list(stringsAsFactors = FALSE)))
  bt$datestamp     <- as.Date(bt$datestamp, origin = "1970-01-01")
  bt$active_return <- bt$port_return - bt$bm_return
  bt$port_tri      <- cumprod(1 + bt$port_return)
  bt$bm_tri        <- cumprod(1 + bt$bm_return)

  mean_active <- mean(bt$active_weight)
  if (mean_active < MIN_ACTIVE_WEIGHT)
    stop(sprintf(paste0("Average total active weight over this window was %.2f%%, below ",
                        "the %.0f%% minimum. Your portfolio barely leaves the benchmark ",
                        "-- take a view."), 100 * mean_active, 100 * MIN_ACTIVE_WEIGHT))

  attr(bt, "violations") <- length(breaches)

  if (verbose) cat(summarise(bt), sep = "\n")
  bt
}

#' Human-readable performance summary of a backtest data.frame.
summarise <- function(bt) {
  n <- nrow(bt)
  # cumulative over the window, not annualised: windows are under a year
  port <- bt$port_tri[n] - 1
  bench <- bt$bm_tri[n] - 1
  active <- bt$active_return
  ir <- if (sd(active) > 0) mean(active) / sd(active) * sqrt(TRADING_DAYS) else 0
  dd <- min(bt$port_tri / cummax(bt$port_tri) - 1)

  c(sprintf("---> window            %s to %s  (%d days)", bt$datestamp[1], bt$datestamp[n], n),
    sprintf("---> portfolio  (net)  %7.2f%%  cumulative", 100 * port),
    sprintf("---> benchmark         %7.2f%%  cumulative", 100 * bench),
    sprintf("---> excess     (net)  %7.2f%%  cumulative", 100 * (bt$port_tri[n] - bt$bm_tri[n])),
    sprintf("---> excess (scored)   %7.3f   bps/day",
            1e4 * (bt$port_tri[n] ^ (1 / n) - bt$bm_tri[n] ^ (1 / n))),
    sprintf("---> information ratio %7.2f", ir),
    sprintf("---> active weight     %7.2f%% average, %.2f%% peak (budget %.0f%%)",
            100 * mean(bt$active_weight), 100 * max(bt$active_weight), 100 * ACTIVE_BUDGET),
    sprintf("---> cost drag         %7.2f%%   avg daily turnover %.2f%%",
            100 * sum(bt$cost), 100 * mean(bt$turnover)),
    sprintf("---> max drawdown      %7.2f%%", 100 * dd))
}

#' Scoring metrics for one window.
metrics <- function(bt) {
  n <- nrow(bt); active <- bt$active_return
  list(days = n,
       port_return   = bt$port_tri[n] - 1,
       bm_return     = bt$bm_tri[n] - 1,
       excess_return = bt$port_tri[n] - bt$bm_tri[n],
       # Scoring metric: mean net excess return PER DAY, in basis points.
       # Deliberately not annualised -- the live window is under a year.
       daily_excess_bps = 1e4 * (bt$port_tri[n] ^ (1 / n) -
                                 bt$bm_tri[n] ^ (1 / n)),
       information_ratio = if (sd(active) > 0)
         mean(active) / sd(active) * sqrt(TRADING_DAYS) else 0,
       realised_te   = sd(active) * sqrt(TRADING_DAYS),
       mean_active_weight = mean(bt$active_weight),
       max_active_weight  = max(bt$active_weight),
       max_exante_te = max(bt$ex_ante_te),
       cost_drag     = sum(bt$cost),
       avg_turnover  = mean(bt$turnover),
       max_drawdown  = min(bt$port_tri / cummax(bt$port_tri) - 1))
}

#' Total-return, weight and active-weight charts (base graphics).
plot_result <- function(bt) {
  op <- par(mfrow = c(3, 1), mar = c(3, 4, 2, 1))
  on.exit(par(op))

  matplot(bt$datestamp, cbind(bt$port_tri, bt$bm_tri), type = "l", lty = 1, lwd = 2,
          col = c("#002855", "#999999"), xlab = "", ylab = "total return index",
          main = "Total return: portfolio vs benchmark")
  legend("topleft", c("your portfolio", "benchmark"), lty = 1, lwd = 2,
         col = c("#002855", "#999999"), bty = "n")

  wm <- t(as.matrix(bt[, paste0("w_", ASSETS)]))
  barplot(wm, col = seq_along(ASSETS), border = NA, space = 0,
          ylab = "weight", main = "Portfolio weights through time", xaxt = "n")
  legend("topright", ASSETS, fill = seq_along(ASSETS), bty = "n", cex = 0.7)

  plot(bt$datestamp, 100 * bt$active_weight, type = "l", col = "#002855", xlab = "",
       ylab = "total active weight (%)", main = "Total active weight",
       ylim = c(0, 100 * ACTIVE_BUDGET * 1.1))
  abline(h = 100 * ACTIVE_BUDGET, lty = 2, col = "#E5554F")
}

# ---- entry point ------------------------------------------------------------

if (sys.nframe() == 0) {
  t0 <- Sys.time()
  cat("---> Prescient Coding Challenge 2026 -- practice window\n")
  source("solution.R")
  result <- run_backtest(generate_weights, PARAMS,
                         start = PRACTICE_WINDOW[1], end = PRACTICE_WINDOW[2])
  cat(sprintf("---> declared parameters: %d\n", length(PARAMS)))
  cat(sprintf("---> run time %.1f seconds\n", as.numeric(difftime(Sys.time(), t0, units = "secs"))))
  plot_result(result)
}
